# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 659d335846b617ebafe7cf7c91f0b88d5ad9046a39477ed50e2cfa8fb0b9eb9e8a07475c94bc9ed971754237a09a2837c839bc79b00a76f2eb57f5bfc22a9550

test:
  secret_key_base: d06472f86c7430aabe99620051c03e13577417e0f53f71ce3ccadcea7ec10abec7efd4f854a5297105ed0649b1d4bb93236ce01158e30fabef6ded4c3a8b3f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
